name: Prettier Code Formatter

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4.0.4
        with:
          node-version: lts/Iron

      - name: Install/Update Prettier
        run: npm install --save-dev --save-exact prettier

      # if prettier find code styles issues, returns 1 (error)
      - name: Prettier Check
        run: npm prettier . --check

      - name: Prettier Write
        if: $({ failure() })
        run: npx prettier . --write --log-level silent
